extends:
  - neko
ignorePatterns:
  - prism.js
  - iconfont.js
  - CHANGELOG.md
rules:
  import/no-unresolved:
    - 2
    - ignore:
      - \\?raw$
      - ^@pkg
      - ^@/
      - components
      - ^neko-ui