extends:
  - neko
  - plugin:solid/recommended
plugins:
  - solid
ignorePatterns:
  - prism.js
  - CHANGELOG.md
rules:
  no-undefined: 0
  '@typescript-eslint/no-namespace': 0
  import/no-unresolved:
    - 2
    - ignore:
        - \\?raw$
        - ^@pkg
        - ^@/
        - components
        - ^neko-ui
        - ^env-flags
overrides:
  - files:
      - '*.mdx'
      - '*.md'
    extends: plugin:mdx/recommended
    parserOptions:
      ecmaVersion: latest
    rules:
      solid/jsx-no-undef: 0
      