extends:
  - neko
rules:
  react/no-unknown-property: off
  no-void: off
  '@typescript-eslint/no-namespace': off
  "@typescript-eslint/no-non-null-assertion": off
ignorePatterns:
  - node_modules/
  - dist/
  - coverage/
  - __snapshots__/
  - prism.js
  - iconfont.js
