extends:
  - neko
  - plugin:solid/recommended
plugins:
  - solid
overrides:
  - files:
      - "*.mdx"
      - "*.md"
    extends: plugin:mdx/recommended
    parserOptions:
      ecmaVersion: latest
    rules:
      solid/jsx-no-undef: 0
rules:
  import/no-unresolved:
    - 2
    - ignore:
        - \\?raw$
        - \\?url$
        - ^@/
        - ^@app
        - ^neko-ui
        - ^http
ignorePatterns: 
  - components/**/examples/*.mdx
