extends:
  - neko
  - plugin:solid/recommended
plugins:
  - solid
rules:
  import/no-unresolved:
    - 2
    - ignore:
        - \\?raw$
        - \\?url$
        - ^@/
        - ^@app
        - ^neko-ui
        - ^http
