extends:
  - neko
  - plugin:solid/recommended
plugins:
  - solid
ignorePatterns:
  - prism.js
  - '*.md'
rules:
  '@typescript-eslint/no-namespace': 0
  import/no-unresolved:
    - 2
    - ignore:
        - \\?raw$
        - ^@/
        - components
        - ^neko-ui
