include:
  - project: ci/npm
    ref: main
    file: ".gitlab-ci.yml"

stages:
  - build
  - deploy

构建:
  only:
    - main
  stage: build
  tags:
    - node-runner
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/
      - yarn.lock
  script:
    - echo '安装依赖'
    - getconf PAGESIZE
    - yarn install
    - echo '开始构建'
    - yarn build
    - echo '构建完成'
  artifacts:
    paths:
      - docs/
      - es/
      - lib/
  retry: 0
